<?php
/**
 * AtroCore Software
 *
 * This source file is available under GNU General Public License version 3 (GPLv3).
 * Full copyright and license information is available in LICENSE.txt, located in the root directory.
 *
 * @copyright  Copyright (c) AtroCore GmbH (https://www.atrocore.com)
 * @license    GPLv3 (https://www.gnu.org/licenses/)
 */

declare(strict_types=1);

namespace Pim\Controllers;

use Atro\Core\Templates\Controllers\Hierarchy;

class Classification extends Hierarchy
{

    public function actionTree($params, $data, $request): array
    {
        return parent::actionTree($params, $data, $request); // TODO: Change the autogenerated stub
    }
}
